defaults:
  -
    values:
      layout: "note"

title: note

collections_dir: ./my_collections
collections:
  categories:
    output: true
    order:
      - bioinfo.md
      - bash.md

plugins:
  - jekyll-titles-from-headings

toc:
  min_level: 1
  max_level: 3
  ordered_list: false
