title: keima-note
description: note for myself.
note-dir: "/note/"
strict_front_matter: true

defaults:
  -
    values:
      layout: "note"

collections_dir: ./my_collections
collections:
  categories:
    output: true
    order:
      - bioinfo.md
      - bash.md
      - R.md

plugins:
  - jekyll-titles-from-headings

toc:
  min_level: 1
  max_level: 3
  ordered_list: false
